# Copyright (C) 2011-2014 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/sony/shinano-common/setup-makefiles.sh

PRODUCT_COPY_FILES += \
    vendor/sony/shinano-common/proprietary/etc/acdbdata/Fluid/Fluid_Bluetooth_cal.acdb:/system/etc/acdbdata/Fluid/Fluid_Bluetooth_cal.acdb \
    vendor/sony/shinano-common/proprietary/etc/acdbdata/Fluid/Fluid_General_cal.acdb:/system/etc/acdbdata/Fluid/Fluid_General_cal.acdb \
    vendor/sony/shinano-common/proprietary/etc/acdbdata/Fluid/Fluid_Global_cal.acdb:/system/etc/acdbdata/Fluid/Fluid_Global_cal.acdb \
    vendor/sony/shinano-common/proprietary/etc/acdbdata/Fluid/Fluid_Handset_cal.acdb:/system/etc/acdbdata/Fluid/Fluid_Handset_cal.acdb \
    vendor/sony/shinano-common/proprietary/etc/acdbdata/Fluid/Fluid_Hdmi_cal.acdb:/system/etc/acdbdata/Fluid/Fluid_Hdmi_cal.acdb \
    vendor/sony/shinano-common/proprietary/etc/acdbdata/Fluid/Fluid_Headset_cal.acdb:/system/etc/acdbdata/Fluid/Fluid_Headset_cal.acdb \
    vendor/sony/shinano-common/proprietary/etc/acdbdata/Fluid/Fluid_Speaker_cal.acdb:/system/etc/acdbdata/Fluid/Fluid_Speaker_cal.acdb \
    vendor/sony/shinano-common/proprietary/etc/acdbdata/Liquid/Liquid_Bluetooth_cal.acdb:/system/etc/acdbdata/Liquid/Liquid_Bluetooth_cal.acdb \
    vendor/sony/shinano-common/proprietary/etc/acdbdata/Liquid/Liquid_General_cal.acdb:/system/etc/acdbdata/Liquid/Liquid_General_cal.acdb \
    vendor/sony/shinano-common/proprietary/etc/acdbdata/Liquid/Liquid_Global_cal.acdb:/system/etc/acdbdata/Liquid/Liquid_Global_cal.acdb \
    vendor/sony/shinano-common/proprietary/etc/acdbdata/Liquid/Liquid_Handset_cal.acdb:/system/etc/acdbdata/Liquid/Liquid_Handset_cal.acdb \
    vendor/sony/shinano-common/proprietary/etc/acdbdata/Liquid/Liquid_Hdmi_cal.acdb:/system/etc/acdbdata/Liquid/Liquid_Hdmi_cal.acdb \
    vendor/sony/shinano-common/proprietary/etc/acdbdata/Liquid/Liquid_Headset_cal.acdb:/system/etc/acdbdata/Liquid/Liquid_Headset_cal.acdb \
    vendor/sony/shinano-common/proprietary/etc/acdbdata/Liquid/Liquid_Speaker_cal.acdb:/system/etc/acdbdata/Liquid/Liquid_Speaker_cal.acdb \
    vendor/sony/shinano-common/proprietary/etc/acdbdata/MTP/MTP_Bluetooth_cal.acdb:/system/etc/acdbdata/MTP/MTP_Bluetooth_cal.acdb \
    vendor/sony/shinano-common/proprietary/etc/acdbdata/MTP/MTP_General_cal.acdb:/system/etc/acdbdata/MTP/MTP_General_cal.acdb \
    vendor/sony/shinano-common/proprietary/etc/acdbdata/MTP/MTP_Global_cal.acdb:/system/etc/acdbdata/MTP/MTP_Global_cal.acdb \
    vendor/sony/shinano-common/proprietary/etc/acdbdata/MTP/MTP_Handset_cal.acdb:/system/etc/acdbdata/MTP/MTP_Handset_cal.acdb \
    vendor/sony/shinano-common/proprietary/etc/acdbdata/MTP/MTP_Hdmi_cal.acdb:/system/etc/acdbdata/MTP/MTP_Hdmi_cal.acdb \
    vendor/sony/shinano-common/proprietary/etc/acdbdata/MTP/MTP_Headset_cal.acdb:/system/etc/acdbdata/MTP/MTP_Headset_cal.acdb \
    vendor/sony/shinano-common/proprietary/etc/acdbdata/MTP/MTP_Speaker_cal.acdb:/system/etc/acdbdata/MTP/MTP_Speaker_cal.acdb \
    vendor/sony/shinano-common/proprietary/etc/acdbdata/Sony/Sony_Bluetooth_cal.acdb:/system/etc/acdbdata/Sony/Sony_Bluetooth_cal.acdb \
    vendor/sony/shinano-common/proprietary/etc/acdbdata/Sony/Sony_General_cal.acdb:/system/etc/acdbdata/Sony/Sony_General_cal.acdb \
    vendor/sony/shinano-common/proprietary/etc/acdbdata/Sony/Sony_Global_cal.acdb:/system/etc/acdbdata/Sony/Sony_Global_cal.acdb \
    vendor/sony/shinano-common/proprietary/etc/acdbdata/Sony/Sony_Handset_cal.acdb:/system/etc/acdbdata/Sony/Sony_Handset_cal.acdb \
    vendor/sony/shinano-common/proprietary/etc/acdbdata/Sony/Sony_Hdmi_cal.acdb:/system/etc/acdbdata/Sony/Sony_Hdmi_cal.acdb \
    vendor/sony/shinano-common/proprietary/etc/acdbdata/Sony/Sony_Headset_cal.acdb:/system/etc/acdbdata/Sony/Sony_Headset_cal.acdb \
    vendor/sony/shinano-common/proprietary/etc/acdbdata/Sony/Sony_Speaker_cal.acdb:/system/etc/acdbdata/Sony/Sony_Speaker_cal.acdb \
    vendor/sony/shinano-common/proprietary/vendor/lib/libbtnv.so:system/vendor/lib/libbtnv.so
