# Copyright (C) 2011-2014 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/sony/shinano-common-widevine/setup-makefiles.sh

PRODUCT_PACKAGES += \
    com.google.widevine.software.drm

PRODUCT_COPY_FILES += \
    vendor/sony/shinano-common-widevine/proprietary/etc/firmware/tzwvcpybuf.b00:system/etc/firmware/tzwvcpybuf.b00 \
    vendor/sony/shinano-common-widevine/proprietary/etc/firmware/tzwvcpybuf.b01:system/etc/firmware/tzwvcpybuf.b01 \
    vendor/sony/shinano-common-widevine/proprietary/etc/firmware/tzwvcpybuf.b02:system/etc/firmware/tzwvcpybuf.b02 \
    vendor/sony/shinano-common-widevine/proprietary/etc/firmware/tzwvcpybuf.b03:system/etc/firmware/tzwvcpybuf.b03 \
    vendor/sony/shinano-common-widevine/proprietary/etc/firmware/tzwvcpybuf.flist:system/etc/firmware/tzwvcpybuf.flist \
    vendor/sony/shinano-common-widevine/proprietary/etc/firmware/tzwvcpybuf.mdt:system/etc/firmware/tzwvcpybuf.mdt \
    vendor/sony/shinano-common-widevine/proprietary/etc/permissions/com.google.widevine.software.drm.xml:system/etc/permissions/com.google.widevine.software.drm.xml \
    vendor/sony/shinano-common-widevine/proprietary/vendor/lib/libWVStreamControlAPI_L3.so:system/vendor/lib/libWVStreamControlAPI_L3.so \
    vendor/sony/shinano-common-widevine/proprietary/vendor/lib/libbtnv.so:system/vendor/lib/libbtnv.so \
    vendor/sony/shinano-common-widevine/proprietary/vendor/lib/libdrmdecrypt.so:system/vendor/lib/libdrmdecrypt.so \
    vendor/sony/shinano-common-widevine/proprietary/vendor/lib/libkeyctrl.so:system/vendor/lib/libkeyctrl.so \
    vendor/sony/shinano-common-widevine/proprietary/vendor/lib/libnpfinal.so:system/vendor/lib/libnpfinal.so \
    vendor/sony/shinano-common-widevine/proprietary/vendor/lib/libwvdrm_L3.so:system/vendor/lib/libwvdrm_L3.so \
    vendor/sony/shinano-common-widevine/proprietary/vendor/lib/libwvm.so:system/vendor/lib/libwvm.so \
    vendor/sony/shinano-common-widevine/proprietary/vendor/lib/drm/libdrmwvmplugin.so:system/vendor/lib/drm/libdrmwvmplugin.so \
    vendor/sony/shinano-common-widevine/proprietary/vendor/lib/mediadrm/libwvdrmengine.so:system/vendor/lib/mediadrm/libwvdrmengine.so
